export interface PeriodicElement {
  number: number;
  symbol: string;
  name: string;
  mass: number;
  period: number;
  group: number | string; // some can be representative, but let's use numbers/strings (1-18)
  category: string;
  state: 'Sólido' | 'Líquido' | 'Gaseoso' | 'Sintético';
}

export const ALL_118_ELEMENTS: PeriodicElement[] = [
  { number: 1, symbol: "H", name: "Hidrógeno", mass: 1.008, period: 1, group: 1, category: "No Metal", state: "Gaseoso" },
  { number: 2, symbol: "He", name: "Helio", mass: 4.0026, period: 1, group: 18, category: "Gases Nobles", state: "Gaseoso" },
  { number: 3, symbol: "Li", name: "Litio", mass: 6.94, period: 2, group: 1, category: "Metales Alcalinos", state: "Sólido" },
  { number: 4, symbol: "Be", name: "Berilio", mass: 9.0122, period: 2, group: 2, category: "Metales de Transición", state: "Sólido" },
  { number: 5, symbol: "B", name: "Boro", mass: 10.81, period: 2, group: 13, category: "Metaloides", state: "Sólido" },
  { number: 6, symbol: "C", name: "Carbono", mass: 12.011, period: 2, group: 14, category: "No Metal", state: "Sólido" },
  { number: 7, symbol: "N", name: "Nitrógeno", mass: 14.007, period: 2, group: 15, category: "No Metal", state: "Gaseoso" },
  { number: 8, symbol: "O", name: "Oxígeno", mass: 15.999, period: 2, group: 16, category: "No Metal", state: "Gaseoso" },
  { number: 9, symbol: "F", name: "Flúor", mass: 18.998, period: 2, group: 17, category: "Halógenos", state: "Gaseoso" },
  { number: 10, symbol: "Ne", name: "Neón", mass: 20.180, period: 2, group: 18, category: "Gases Nobles", state: "Gaseoso" },
  { number: 11, symbol: "Na", name: "Sodio", mass: 22.990, period: 3, group: 1, category: "Metales Alcalinos", state: "Sólido" },
  { number: 12, symbol: "Mg", name: "Magnesio", mass: 24.305, period: 3, group: 2, category: "Metales de Transición", state: "Sólido" },
  { number: 13, symbol: "Al", name: "Aluminio", mass: 26.982, period: 3, group: 13, category: "Metaloides", state: "Sólido" },
  { number: 14, symbol: "Si", name: "Silicio", mass: 28.085, period: 3, group: 14, category: "Metaloides", state: "Sólido" },
  { number: 15, symbol: "P", name: "Fósforo", mass: 30.974, period: 3, group: 15, category: "No Metal", state: "Sólido" },
  { number: 16, symbol: "S", name: "Azufre", mass: 32.06, period: 3, group: 16, category: "No Metal", state: "Sólido" },
  { number: 17, symbol: "Cl", name: "Cloro", mass: 35.45, period: 3, group: 17, category: "Halógenos", state: "Gaseoso" },
  { number: 18, symbol: "Ar", name: "Argón", mass: 39.948, period: 3, group: 18, category: "Gases Nobles", state: "Gaseoso" },
  { number: 19, symbol: "K", name: "Potasio", mass: 39.098, period: 4, group: 1, category: "Metales Alcalinos", state: "Sólido" },
  { number: 20, symbol: "Ca", name: "Calcio", mass: 40.078, period: 4, group: 2, category: "Metales de Transición", state: "Sólido" },
  { number: 21, symbol: "Sc", name: "Escandio", mass: 44.956, period: 4, group: 3, category: "Metales de Transición", state: "Sólido" },
  { number: 22, symbol: "Ti", name: "Titanio", mass: 47.867, period: 4, group: 4, category: "Metales de Transición", state: "Sólido" },
  { number: 23, symbol: "V", name: "Vanadio", mass: 50.942, period: 4, group: 5, category: "Metales de Transición", state: "Sólido" },
  { number: 24, symbol: "Cr", name: "Cromo", mass: 51.996, period: 4, group: 6, category: "Metales de Transición", state: "Sólido" },
  { number: 25, symbol: "Mn", name: "Manganeso", mass: 54.938, period: 4, group: 7, category: "Metales de Transición", state: "Sólido" },
  { number: 26, symbol: "Fe", name: "Hierro", mass: 55.845, period: 4, group: 8, category: "Metales de Transición", state: "Sólido" },
  { number: 27, symbol: "Co", name: "Cobalto", mass: 58.933, period: 4, group: 9, category: "Metales de Transición", state: "Sólido" },
  { number: 28, symbol: "Ni", name: "Níquel", mass: 58.693, period: 4, group: 10, category: "Metales de Transición", state: "Sólido" },
  { number: 29, symbol: "Cu", name: "Cobre", mass: 63.546, period: 4, group: 11, category: "Metales de Transición", state: "Sólido" },
  { number: 30, symbol: "Zn", name: "Zinc", mass: 65.38, period: 4, group: 12, category: "Metales de Transición", state: "Sólido" },
  { number: 31, symbol: "Ga", name: "Galio", mass: 69.723, period: 4, group: 13, category: "Metales de Transición", state: "Sólido" },
  { number: 32, symbol: "Ge", name: "Germanio", mass: 72.63, period: 4, group: 14, category: "Metaloides", state: "Sólido" },
  { number: 33, symbol: "As", name: "Arsénico", mass: 74.922, period: 4, group: 15, category: "Metaloides", state: "Sólido" },
  { number: 34, symbol: "Se", name: "Selenio", mass: 78.971, period: 4, group: 16, category: "No Metal", state: "Sólido" },
  { number: 35, symbol: "Br", name: "Bromo", mass: 79.904, period: 4, group: 17, category: "Halógenos", state: "Líquido" },
  { number: 36, symbol: "Kr", name: "Kriptón", mass: 83.798, period: 4, group: 18, category: "Gases Nobles", state: "Gaseoso" },
  { number: 37, symbol: "Rb", name: "Rubidio", mass: 85.468, period: 5, group: 1, category: "Metales Alcalinos", state: "Sólido" },
  { number: 38, symbol: "Sr", name: "Estroncio", mass: 87.62, period: 5, group: 2, category: "Metales de Transición", state: "Sólido" },
  { number: 39, symbol: "Y", name: "Itrio", mass: 88.906, period: 5, group: 3, category: "Metales de Transición", state: "Sólido" },
  { number: 40, symbol: "Zr", name: "Zirconio", mass: 91.224, period: 5, group: 4, category: "Metales de Transición", state: "Sólido" },
  { number: 41, symbol: "Nb", name: "Niobio", mass: 92.906, period: 5, group: 5, category: "Metales de Transición", state: "Sólido" },
  { number: 42, symbol: "Mo", name: "Molibdeno", mass: 95.95, period: 5, group: 6, category: "Metales de Transición", state: "Sólido" },
  { number: 43, symbol: "Tc", name: "Tecnecio", mass: 98, period: 5, group: 7, category: "Metales de Transición", state: "Sintético" },
  { number: 44, symbol: "Ru", name: "Rutenio", mass: 101.07, period: 5, group: 8, category: "Metales de Transición", state: "Sólido" },
  { number: 45, symbol: "Rh", name: "Rodio", mass: 102.91, period: 5, group: 9, category: "Metales de Transición", state: "Sólido" },
  { number: 46, symbol: "Pd", name: "Paladio", mass: 106.42, period: 5, group: 10, category: "Metales de Transición", state: "Sólido" },
  { number: 47, symbol: "Ag", name: "Plata", mass: 107.87, period: 5, group: 11, category: "Metales de Transición", state: "Sólido" },
  { number: 48, symbol: "Cd", name: "Cadmio", mass: 112.41, period: 5, group: 12, category: "Metales de Transición", state: "Sólido" },
  { number: 49, symbol: "In", name: "Indio", mass: 114.82, period: 5, group: 13, category: "Metales de Transición", state: "Sólido" },
  { number: 50, symbol: "Sn", name: "Estaño", mass: 118.71, period: 5, group: 14, category: "Metales de Transición", state: "Sólido" },
  { number: 51, symbol: "Sb", name: "Antimonio", mass: 121.76, period: 5, group: 15, category: "Metaloides", state: "Sólido" },
  { number: 52, symbol: "Te", name: "Telurio", mass: 127.6, period: 5, group: 16, category: "Metaloides", state: "Sólido" },
  { number: 53, symbol: "I", name: "Yodo", mass: 126.90, period: 5, group: 17, category: "Halógenos", state: "Sólido" },
  { number: 54, symbol: "Xe", name: "Xenón", mass: 131.29, period: 5, group: 18, category: "Gases Nobles", state: "Gaseoso" },
  { number: 55, symbol: "Cs", name: "Cesio", mass: 132.91, period: 6, group: 1, category: "Metales Alcalinos", state: "Sólido" },
  { number: 56, symbol: "Ba", name: "Bario", mass: 137.33, period: 6, group: 2, category: "Metales de Transición", state: "Sólido" },
  { number: 57, symbol: "La", name: "Lantano", mass: 138.91, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 58, symbol: "Ce", name: "Cerio", mass: 140.12, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 59, symbol: "Pr", name: "Praseodimio", mass: 140.91, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 60, symbol: "Nd", name: "Neodimio", mass: 144.24, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 61, symbol: "Pm", name: "Prometio", mass: 145, period: 6, group: "Lantánido", category: "Lantánido", state: "Sintético" },
  { number: 62, symbol: "Sm", name: "Samario", mass: 150.36, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 63, symbol: "Eu", name: "Europio", mass: 151.96, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 64, symbol: "Gd", name: "Gadolinio", mass: 157.25, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 65, symbol: "Tb", name: "Terbio", mass: 158.93, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 66, symbol: "Dy", name: "Disprosio", mass: 162.50, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 67, symbol: "Ho", name: "Holmio", mass: 164.93, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 68, symbol: "Er", name: "Erbio", mass: 167.26, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 69, symbol: "Tm", name: "Tulio", mass: 168.93, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 70, symbol: "Yb", name: "Iterbio", mass: 173.05, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 71, symbol: "Lu", name: "Lutecio", mass: 174.97, period: 6, group: "Lantánido", category: "Lantánido", state: "Sólido" },
  { number: 72, symbol: "Hf", name: "Hafnio", mass: 178.49, period: 6, group: 4, category: "Metales de Transición", state: "Sólido" },
  { number: 73, symbol: "Ta", name: "Tántalo", mass: 180.95, period: 6, group: 5, category: "Metales de Transición", state: "Sólido" },
  { number: 74, symbol: "W", name: "Wolframio", mass: 183.84, period: 6, group: 6, category: "Metales de Transición", state: "Sólido" },
  { number: 75, symbol: "Re", name: "Renio", mass: 186.21, period: 6, group: 7, category: "Metales de Transición", state: "Sólido" },
  { number: 76, symbol: "Os", name: "Osmio", mass: 190.23, period: 6, group: 8, category: "Metales de Transición", state: "Sólido" },
  { number: 77, symbol: "Ir", name: "Iridio", mass: 192.22, period: 6, group: 9, category: "Metales de Transición", state: "Sólido" },
  { number: 78, symbol: "Pt", name: "Platino", mass: 195.08, period: 6, group: 10, category: "Metales de Transición", state: "Sólido" },
  { number: 79, symbol: "Au", name: "Oro", mass: 196.97, period: 6, group: 11, category: "Metales de Transición", state: "Sólido" },
  { number: 80, symbol: "Hg", name: "Mercurio", mass: 200.59, period: 6, group: 12, category: "Metales de Transición", state: "Líquido" },
  { number: 81, symbol: "Tl", name: "Talio", mass: 204.38, period: 6, group: 13, category: "Metales de Transición", state: "Sólido" },
  { number: 82, symbol: "Pb", name: "Plomo", mass: 207.2, period: 6, group: 14, category: "Metales de Transición", state: "Sólido" },
  { number: 83, symbol: "Bi", name: "Bismuto", mass: 208.98, period: 6, group: 15, category: "Metales de Transición", state: "Sólido" },
  { number: 84, symbol: "Po", name: "Polonio", mass: 209, period: 6, group: 16, category: "Metaloides", state: "Sólido" },
  { number: 85, symbol: "At", name: "Astato", mass: 210, period: 6, group: 17, category: "Halógenos", state: "Sólido" },
  { number: 86, symbol: "Rn", name: "Radón", mass: 222, period: 6, group: 18, category: "Gases Nobles", state: "Gaseoso" },
  { number: 87, symbol: "Fr", name: "Francio", mass: 223, period: 7, group: 1, category: "Metales Alcalinos", state: "Sólido" },
  { number: 88, symbol: "Ra", name: "Radio", mass: 226, period: 7, group: 2, category: "Metales de Transición", state: "Sólido" },
  { number: 89, symbol: "Ac", name: "Actinio", mass: 227, period: 7, group: "Actínido", category: "Actínido", state: "Sólido" },
  { number: 90, symbol: "Th", name: "Torio", mass: 232.04, period: 7, group: "Actínido", category: "Actínido", state: "Sólido" },
  { number: 91, symbol: "Pa", name: "Protactinio", mass: 231.04, period: 7, group: "Actínido", category: "Actínido", state: "Sólido" },
  { number: 92, symbol: "U", name: "Uranio", mass: 238.03, period: 7, group: "Actínido", category: "Actínido", state: "Sólido" },
  { number: 93, symbol: "Np", name: "Neptunio", mass: 237, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 94, symbol: "Pu", name: "Plutonio", mass: 244, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 95, symbol: "Am", name: "Americio", mass: 243, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 96, symbol: "Cm", name: "Curio", mass: 247, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 97, symbol: "Bk", name: "Berkelio", mass: 247, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 98, symbol: "Cf", name: "Californio", mass: 251, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 99, symbol: "Es", name: "Einsteinio", mass: 252, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 100, symbol: "Fm", name: "Fermio", mass: 257, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 101, symbol: "Md", name: "Mendelevio", mass: 258, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 102, symbol: "No", name: "Nobelio", mass: 259, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 103, symbol: "Lr", name: "Laurencio", mass: 262, period: 7, group: "Actínido", category: "Actínido", state: "Sintético" },
  { number: 104, symbol: "Rf", name: "Rutherfordio", mass: 267, period: 7, group: 4, category: "Metales de Transición", state: "Sintético" },
  { number: 105, symbol: "Db", name: "Dubnio", mass: 268, period: 7, group: 5, category: "Metales de Transición", state: "Sintético" },
  { number: 106, symbol: "Sg", name: "Seaborgio", mass: 271, period: 7, group: 6, category: "Metales de Transición", state: "Sintético" },
  { number: 107, symbol: "Bh", name: "Bohrio", mass: 272, period: 7, group: 7, category: "Metales de Transición", state: "Sintético" },
  { number: 108, symbol: "Hs", name: "Hassio", mass: 270, period: 7, group: 8, category: "Metales de Transición", state: "Sintético" },
  { number: 109, symbol: "Mt", name: "Meitnerio", mass: 276, period: 7, group: 9, category: "Metales de Transición", state: "Sintético" },
  { number: 110, symbol: "Ds", name: "Darmstadtio", mass: 281, period: 7, group: 10, category: "Metales de Transición", state: "Sintético" },
  { number: 111, symbol: "Rg", name: "Roentgenio", mass: 282, period: 7, group: 11, category: "Metales de Transición", state: "Sintético" },
  { number: 112, symbol: "Cn", name: "Copernicio", mass: 285, period: 7, group: 12, category: "Metales de Transición", state: "Sintético" },
  { number: 113, symbol: "Nh", name: "Nihonio", mass: 286, period: 7, group: 13, category: "Metales de Transición", state: "Sintético" },
  { number: 114, symbol: "Fl", name: "Flerovio", mass: 289, period: 7, group: 14, category: "Metales de Transición", state: "Sintético" },
  { number: 115, symbol: "Mc", name: "Moscovio", mass: 290, period: 7, group: 15, category: "Metales de Transición", state: "Sintético" },
  { number: 116, symbol: "Lv", name: "Livermorio", mass: 293, period: 7, group: 16, category: "Metales de Transición", state: "Sintético" },
  { number: 117, symbol: "Ts", name: "Teneso", mass: 294, period: 7, group: 17, category: "Halógenos", state: "Sintético" },
  { number: 118, symbol: "Og", name: "Oganesón", mass: 294, period: 7, group: 18, category: "Gases Nobles", state: "Sintético" }
];
